### PR TITLE
Add missing dependency "p-limit" in package.json

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by zckrs** [comment]
Can someone can release this PR ? @simonswine @nwalters512

**Comment by korniltsev** [comment]
@zckrs Can you provide some more info? Why do we need this? Did you get any errors?

**Comment by korniltsev** [comment]
Should we also update yarn.lock ?

**Comment by zckrs** [comment]
Sorry for missing informations.

In https://github.com/grafana/pyroscope-nodejs/blob/663a557fa0e570232c9c1ad639211430fbc6eaef/src/sourcemapper.ts#L27 `p-limit` is used but is not present in package.json.

npm doesnt install the pacakge in most case with a small project.

For example in our prod environnement with `npm install --only=production`


```
Cannot find module 'p-limit'Require stack:
- /src/node_modules/@pyroscope/nodejs/dist/cjs/sourcemapper.js
- /src/node_modules/@pyroscope/nodejs/dist/cjs/index.js
- /src/node_modules/our-express/src/boot/pyroscope.js
- /src/node_modules/our-express/src/index.js
- /src/server/server.js
- /src/server/reader.js Require stack: 
- node_modules/@pyroscope/nodejs/dist/cjs/sourcemapper.js 
- node_modules/@pyroscope/nodejs/dist/cjs/index.js 
- node_modules/our-express/src/boot/pyroscope.js 
- node_modules/our-express/src/index.js 
- server/server.js 
- server/reader.js at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15) at Module._load (node:internal/modules/cjs/loader:1051:27) at Module.require (node:internal/modules/cjs/loader:1311:19) at require (node:internal/modules/helpers:179:18) at Object.<anonymous> (node_modules/@pyroscope/nodejs/dist/cjs/sourcemapper.js:54:35) at Module._compile (node:internal/modules/cjs/loader:1469:14) at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) at Module.load (node:internal/modules/cjs/loader:1288:32) at Module._load (node:internal/modules/cjs/loader:1104:12) at Module.require (node:internal/modules/cjs/loader:1311:19)
```

**Review by korniltsev — APPROVED** [review]

**Comment by zckrs** [comment]
Do you plan to release a patch version ?

**Comment by zckrs** [comment]
Please release a 0.4.1 :pray: @korniltsev

**Comment by bryanhuhta** [comment]
@zckrs I just release [v0.4.1](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.1).

**Pull request merged**
