### PR TITLE
chore: update import paths to use .js file extensions

### PR DESCRIPTION
**Pull request by zckrs**
To follow https://github.com/grafana/pyroscope-nodejs/issues/32, https://github.com/grafana/pyroscope-nodejs/pull/33 and fix build for ESM

### CODE REVIEW

**Comment by bryanhuhta** [comment]
:wave: Hey @zckrs! Thanks for this contribution. I just merged some lint changes (requiring semicolons) which created a lot of conflicts with this PR. I also ran CI on this PR and it looks like specifying `.js` in the imports is breaking many of the tests. I am investigating this right now.

**Comment by zckrs** [comment]
Hi @bryanhuhta  :wave: 

I just rebase on main and reapply diff

How can I help you to merge this ?

**Comment by bryanhuhta** [comment]
@zckrs I appreciate your patience 🙇 

I validated this patch works on both a ESM project and a CJS one, but the test suite does not appreciate these changes. When I run the tests, I get lots of

```
 FAIL  test/profiler.test.ts
  ● Test suite failed to run

    Cannot find module '../src/index.js' from 'test/profiler.test.ts'

    > 1 | import Pyroscope from '../src/index.js';
        | ^
      2 | import express from 'express';
      3 | import busboy from 'busboy';
      4 | import { Profile } from 'pprof-format';

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (test/profiler.test.ts:1:1)
```

Presumably because there is a mismatch between how jest is configured to resolve modules and how the modules are built. I've been trying to find a solution, but my free time is limited. The only blocker to this change is making sure the test suite can run with these changes in place.

**Comment by zckrs** [comment]
In fact Jest doesn't have a good support for ESM :/ 

https://jestjs.io/docs/ecmascript-modules

**Comment by nwalters512** [comment]
I went ahead and opened https://github.com/grafana/pyroscope-nodejs/pull/94 to migrate to Vitest. Hopefully that can unblock proper ESM support.

**Comment by bryanhuhta** [comment]
@zckrs I just merged a few PRs which should unblock this PR:

- https://github.com/grafana/pyroscope-nodejs/pull/90
- https://github.com/grafana/pyroscope-nodejs/pull/94
- https://github.com/grafana/pyroscope-nodejs/pull/95

Can you merge `origin/main` and fix the merge conflicts? I'll approve and merge this PR after that, then cut a new release.

**Comment by nwalters512** [comment]
I tested these changes locally on top of the latest `main`. Tests are passing, and the output in `dist/` looks as it should! 🎉

Very excited to see this land.

**Comment by zckrs** [comment]
Hi,
Need to sleep but after that I will rebase from main branch 😉

**Review by bryanhuhta — APPROVED** [review]

**Comment by bryanhuhta** [comment]
@zckrs @nwalters512 I merged this and released [`v0.4.0`](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.0). Let me know if there's any problems that arise!

**Pull request merged**
